### ISSUE TITLE
Data:  grunt.file.readJSON ReferenceError: grunt is not defined

### ISSUE THREAD

**Issue by rludgero** [denkwerk/grunt-nunjuckr#1] opened 2016-01-30 20:18 UTC
Hi, thanks for sharing this plugin.

I created my configuration of nunjuckr to compile my templates, so far all ok, the problem I'm having is assigned when the data property.

> options: {data: grunt.file.readJSON('data/data.json')}
##### When i compile with grunt nunjuckr command, the terminal prints this:

> ReferenceError: grunt is not defined

There any way that instead of spending **grunt.file.readJSON('data/data.json')**, use a string with the path where the files are located like this:

```
options: {
    data: 'data/data.json'
}
```

or

```
options: {
    data: 'data/**/*.json'
}
```

or

```
options: {
    data: ['data/data.json', 'data/other.json']
}
```

Thanks in advance

**Comment by mariusbuescher** [comment] 2016-01-31 10:18
The `data` option expects a JavaScript object. The `grunt.file.readJSON` has nothing to do with `grunt-nunjuckr`, it is a simple function coming with grunt. See [http://gruntjs.com/api/grunt.file#grunt.file.readjson](http://gruntjs.com/api/grunt.file#grunt.file.readjson).

Maybe the problem is within your `Gruntfile.js`. Did you pass `grunt` as an argument in the function you export? See [Gruntfile.js](https://github.com/denkwerk/grunt-nunjuckr/blob/master/Gruntfile.js). Maybe you can paste it here and I can fix the problem.

**Comment by rludgero** [comment] 2016-01-31 12:30
Hi @mariusbuescher, thanks for answering quickly.
Maybe it's because I'm using load-grunt-config.

**The nunjuckr.js file:**

```
module.exports = {
    nunjucks: {
        options: {
            data: grunt.file.readJSON('data/data.json'),
            ext: '.html',
            // path to find all nunjucks template files
            searchPaths: '<%= environmentPath.development %>/templates/'
        },
        files: [{
            // Enable dynamic expansion.
            expand: true,
            // All src matches are relative to (but don't include) this path.
            cwd: '<%= environmentPath.development %>/',
            // Pattern(s) to match, relative to the cwd
            // path to nunjucks files, that we want convert to html
            src: 'templates/content-types/**/*.njs',
            // Destination path
            dest: '<%= environmentPath.development %>/'
        }]
    }
};
```

##### I tried to pass this argument to the function inside nunjuckr.js file like that:

```
module.exports = function(grunt) {
    return {
        nunjucks: {
            options: {
                data: grunt.file.readJSON('data/data.json'),
                ext: '.html',
                // path to find all nunjucks template files
                searchPaths: '<%= environmentPath.development %>/templates/'
            },
            files: [{
                // Enable dynamic expansion.
                expand: true,
                // All src matches are relative to (but don't include) this path.
                cwd: '<%= environmentPath.development %>/',
                // Pattern(s) to match, relative to the cwd
                // path to nunjucks files, that we want convert to html
                src: 'templates/content-types/**/*.njs',
                // Destination path
                dest: '<%= environmentPath.development %>/'
            }]
        }
    }
};
```

but I could not get it to work.

**Gruntfile.js**

```
module.exports = function(grunt) {

    'use strict';
    // global variable path
    var environmentPath = {
        production: './dist',
        development: './src'
    };

    // global variable path
    var assetsPath = {
        production: '<%= environmentPath.production %>/assets',
        development: '<%= environmentPath.development %>/assets'
    };

    // global variable path
    var localhostPath = {
        production: 'http://localhost:8000',
        development: 'http://localhost:8000'
    };

    // this is necessary for time-grunt plugin
    require('time-grunt')(grunt);

    // this is necessary for load-grunt-config plugin
    var path = require('path');

    // this is necessary for load-grunt-config plugin
    require('load-grunt-config')(grunt, {
        // this config depends of var path = require('path');
        // the parameter is to sign a content folder tasks-files.js
        configPath: path.join(process.cwd(), 'tasks'),
        config: {
            // var environmentPath scope
            environmentPath: environmentPath,

            // var assetsPath scope
            assetsPath: assetsPath,

            // var localhostPath scope
            localhostPath: localhostPath
        },
        // load all tasks
        jitGrunt: true
    });
```

Regards.

**Comment by rludgero** [comment] 2016-01-31 13:50
@mariusbuescher i found the solution, is a load-grunt-config settings, its not grunt-nunjuckr problem.
Thanks for your attention.

```
module.exports = function(grunt) {
    return {
        nunjucks: {
            options: {
                data: grunt.file.readJSON('src/templates/data/data.json'),
                ext: '.html',
                // path to find all nunjucks template files
                searchPaths: '<%= environmentPath.development %>/templates/'
            },
            files: [{
                // Pattern(s) to match, relative to the cwd
                // path to nunjucks files, that we want convert to html
                src: '<%= environmentPath.development %>/templates/content-types/**/*.njs',
                // Destination path
                dest: '<%= environmentPath.development %>/'
            }]
        }
    }
};
```

Cheers.

**Comment by mariusbuescher** [comment] 2016-01-31 17:37
So this is no issue of `grunt-nunjuckr`. I will close this.

**Closed as completed by mariusbuescher** 2016-01-31 17:37 UTC
